package code.rules

import code.model.*;

rule "Rule 1"
    when
        Transaction(
          valid_card == true,
          expired == false,
          pin_correct == true,
          attempts < 3,
          balance_after >= 0,
          amount <= 500,
          transaction_type == "withdraw",
          confirmed == true
        )
    then
        insert( new Approval( "Withdrawal approved", true ) );
end

rule "Rule 2"
    when
        Transaction(
          valid_card == false
        )
    then
        insert( new Approval( "Withdrawal approved", false ) );
end

rule "Rule 3"
    when
        Transaction(
          expired == true
        )
    then
        insert( new Approval( "Withdrawal approved", false) );
end

rule "Rule 4"
    when
        Transaction(
          pin_correct == false
        )
    then
        insert( new Approval( "Withdrawal approved", false ) );
end

rule "Rule 5"
    when
        Transaction(
          attempts >= 3
        )
    then
        insert( new Approval( "Withdrawal approved", false ) );
end

rule "Rule 6"
    when
        Transaction(
          balance_after < 0
        )
    then
        insert( new Approval( "Withdrawal approved", false ) );
end

rule "Rule 7"
    when
        Transaction(
          amount > 500
        )
    then
        insert( new Approval( "Withdrawal approved", false ) );
end

rule "Rule 8"
    when
        Transaction(
          valid_card == true,
          expired == false,
          pin_correct == true,
          attempts < 3,
          balance_after >= 0,
          amount <= 500,
          transaction_type == "dui",
          confirmed == true
        )
    then
        insert( new Approval( "Withdrawal approved", true ) );
end

rule "Rule 9"
    when
        Transaction(
          confirmed == false
        )
    then
        insert( new Approval( "Withdrawal approved", false ) );
end

rule "Rule 10"
    when
        Transaction(
          valid_card == true,
          expired == false,
          pin_correct == true,
          attempts == 1,
          confirmed == true,
          transaction_type == "print"
        )
    then
        insert( new Approval( "Print approved", true ) );
end

rule "Rule 11"
    when
        Transaction(
          bank == "Banco Nacional de Bolivia"
        )
    then
        insert( new Commission( 12 ) );
end

rule "Rule 12"
    when
        Transaction(
          bank == "Banco Sol"
        )
    then
        insert( new Commission( 35 ) );
end

rule "Rule 13"
    when
        Transaction(
          bank == "Banco Mercantil Santa Cruz"
        )
    then
        insert( new Commission( 12 ) );
end

rule "Rule 14"
    when
        Transaction(
          bank == "Banco Ganadero"
        )
    then
        insert( new Commission( 20 ) );
end

rule "Rule 15"
    when
        ATMBalance(balance <= 0)
    then
        insert( new Approval( "Withdrawal approved", false ) );
end


